spring:
  application:
    name: CourseTrackAPI
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: appuser
    password: APPUSER
jpa:
  hibernate:
    ddl-auto: create