spring:
  application:
    name: CourseTrackAPI
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: appuser
    password: APPUSER
SMSNotification: false
email-notification-service:
  host: codeRed@gmail.com
  port: 8080
